##import the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Import the dataset

[Click here to download placement_data.csv](https://drive.google.com/file/d/1cfwWkblzkzwK6bArczlTnU71FlQz-FZq/view?usp=share_link)

In [2]:
data = pd.read_csv('Placement_Data.csv')
x = data.iloc[:, :-2].values
y = data.iloc[:, -1].values

In [4]:
data.head()

ssc_p  hsc_p     hsc_s  degree_p workex  etest_p  mba_p      status  \
0  67.00  91.00  Commerce     58.00     No     55.0  58.80      Placed   
1  79.33  78.33   Science     77.48    Yes     86.5  66.28      Placed   
2  65.00  68.00      Arts     64.00     No     75.0  57.80      Placed   
3  56.00  52.00   Science     52.00     No     66.0  59.43  Not Placed   
4  85.80  73.60  Commerce     73.30     No     96.8  55.50      Placed   

     salary  
0  270000.0  
1  200000.0  
2  250000.0  
3       NaN  
4  425000.0

In [6]:
print(x)

[[67.0 91.0 'Commerce' ... 'No' 55.0 58.8]
 [79.33 78.33 'Science' ... 'Yes' 86.5 66.28]
 [65.0 68.0 'Arts' ... 'No' 75.0 57.8]
 ...
 [67.0 67.0 'Commerce' ... 'Yes' 59.0 69.72]
 [74.0 66.0 'Commerce' ... 'No' 70.0 60.23]
 [62.0 58.0 'Science' ... 'No' 89.0 60.22]]


In [7]:
print(y)

[270000. 200000. 250000.     nan 425000.     nan     nan 252000. 231000.
     nan 260000. 250000.     nan 218000.     nan 200000. 300000.     nan
     nan 236000. 265000. 393000. 360000. 300000. 360000.     nan 240000.
 265000. 350000.     nan 250000.     nan 278000. 260000.     nan 300000.
     nan 320000. 240000. 411000. 287000.     nan     nan 300000. 200000.
     nan     nan 204000. 250000.     nan 200000.     nan     nan 450000.
 216000. 220000. 240000. 360000. 268000. 265000. 260000. 300000. 240000.
     nan 240000.     nan 275000. 275000.     nan 275000. 360000. 240000.
 240000. 218000. 336000.     nan 230000. 500000. 270000.     nan 240000.
 300000.     nan 300000. 300000. 400000. 220000.     nan 210000. 210000.
 300000.     nan 230000.     nan 260000. 420000. 300000.     nan 220000.
     nan     nan 380000. 300000. 240000. 360000.     nan     nan 200000.
 300000.     nan 250000.     nan 250000. 280000. 250000. 216000. 300000.
 240000. 276000. 940000.     nan 250000. 236000. 24

#Step-01. Handle missing data

In [8]:
from sklearn.impute import SimpleImputer
imputer_y = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer_y.fit(y.reshape(-1,1))
y = imputer_y.transform(y.reshape(-1,1))

In [9]:
print(y)

[[270000.        ]
 [200000.        ]
 [250000.        ]
 [288655.40540541]
 [425000.        ]
 [288655.40540541]
 [288655.40540541]
 [252000.        ]
 [231000.        ]
 [288655.40540541]
 [260000.        ]
 [250000.        ]
 [288655.40540541]
 [218000.        ]
 [288655.40540541]
 [200000.        ]
 [300000.        ]
 [288655.40540541]
 [288655.40540541]
 [236000.        ]
 [265000.        ]
 [393000.        ]
 [360000.        ]
 [300000.        ]
 [360000.        ]
 [288655.40540541]
 [240000.        ]
 [265000.        ]
 [350000.        ]
 [288655.40540541]
 [250000.        ]
 [288655.40540541]
 [278000.        ]
 [260000.        ]
 [288655.40540541]
 [300000.        ]
 [288655.40540541]
 [320000.        ]
 [240000.        ]
 [411000.        ]
 [287000.        ]
 [288655.40540541]
 [288655.40540541]
 [300000.        ]
 [200000.        ]
 [288655.40540541]
 [288655.40540541]
 [204000.        ]
 [250000.        ]
 [288655.40540541]
 [200000.        ]
 [288655.40540541]
 [288655.405

#Step-02. Encoding categorical data that doesn't have binary result

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [11]:
print(x)

[[0.0 1.0 0.0 ... 'No' 55.0 58.8]
 [0.0 0.0 1.0 ... 'Yes' 86.5 66.28]
 [1.0 0.0 0.0 ... 'No' 75.0 57.8]
 ...
 [0.0 1.0 0.0 ... 'Yes' 59.0 69.72]
 [0.0 1.0 0.0 ... 'No' 70.0 60.23]
 [0.0 0.0 1.0 ... 'No' 89.0 60.22]]


#Step-03. Encoding categorical data that have binary result

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 6] = le.fit_transform(x[:, 6])

In [13]:
print(x)

[[0.0 1.0 0.0 ... 0 55.0 58.8]
 [0.0 0.0 1.0 ... 1 86.5 66.28]
 [1.0 0.0 0.0 ... 0 75.0 57.8]
 ...
 [0.0 1.0 0.0 ... 1 59.0 69.72]
 [0.0 1.0 0.0 ... 0 70.0 60.23]
 [0.0 0.0 1.0 ... 0 89.0 60.22]]


#Step-04. Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [15]:
print(x)

[[-0.23221018  0.95008151 -0.85666269 ... -0.72444647 -1.29109087
  -0.59764672]
 [-0.23221018 -1.05254128  1.16732059 ...  1.38036423  1.08715679
   0.6876202 ]
 [ 4.30644338 -1.05254128 -0.85666269 ... -0.72444647  0.21890765
  -0.76947385]
 ...
 [-0.23221018  0.95008151 -0.85666269 ...  1.38036423 -0.98909117
   1.27870553]
 [-0.23221018  0.95008151 -0.85666269 ... -0.72444647 -0.15859198
  -0.35193393]
 [-0.23221018 -1.05254128  1.16732059 ... -0.72444647  1.27590661
  -0.3536522 ]]


#Step-05. Splitting the data into the Training set and Test set

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [19]:
print(x_train)

[[-0.23221018  0.95008151 -0.85666269 ... -0.72444647 -0.00759213
  -1.18014069]
 [-0.23221018 -1.05254128  1.16732059 ...  1.38036423 -1.29109087
  -0.04779991]
 [-0.23221018  0.95008151 -0.85666269 ...  1.38036423  1.76363613
  -0.02030757]
 ...
 [-0.23221018 -1.05254128  1.16732059 ... -0.72444647 -0.00759213
  -0.48252255]
 [-0.23221018 -1.05254128  1.16732059 ... -0.72444647  0.25665761
   1.69452718]
 [-0.23221018  0.95008151 -0.85666269 ...  1.38036423 -1.10234106
  -0.16636063]]


In [20]:
print(x_test)

[[-0.23221018  0.95008151 -0.85666269  0.15706399 -0.58251317 -0.18663291
  -0.72444647  1.16643172 -1.62689123]
 [-0.23221018  0.95008151 -0.85666269 -0.02808697  0.06133451  0.90304633
   1.38036423 -0.98909117  1.27870553]
 [-0.23221018 -1.05254128  1.16732059  1.36054521 -0.21460021  0.90304633
   1.38036423  1.80440609  1.63095114]
 [-0.23221018  0.95008151 -0.85666269 -0.7686908  -0.58251317 -1.41252206
  -0.72444647 -1.29109087 -0.75229114]
 [-0.23221018  0.95008151 -0.85666269 -0.21323793  0.79716044  0.35820671
   1.38036423 -0.00759213  0.40926025]
 [-0.23221018 -1.05254128  1.16732059 -1.50929463 -1.13438262 -0.73147253
  -0.72444647 -0.91359124 -0.28148481]
 [-0.23221018  0.95008151 -0.85666269 -1.78702107 -1.41031735 -1.14010225
   1.38036423 -0.91359124 -0.59936499]
 [-0.23221018  0.95008151 -0.85666269 -0.25026812  1.60932831  0.72869765
  -0.72444647  1.04940683 -0.43441095]
 [-0.23221018  0.95008151 -0.85666269  0.61994138  0.61320396  0.90304633
   1.38036423  0.59640

In [21]:
print(y_train)

[[288655.40540541]
 [300000.        ]
 [420000.        ]
 [225000.        ]
 [400000.        ]
 [220000.        ]
 [285000.        ]
 [240000.        ]
 [240000.        ]
 [360000.        ]
 [288655.40540541]
 [288655.40540541]
 [288655.40540541]
 [236000.        ]
 [275000.        ]
 [288655.40540541]
 [260000.        ]
 [288655.40540541]
 [288655.40540541]
 [288655.40540541]
 [240000.        ]
 [288655.40540541]
 [288655.40540541]
 [288655.40540541]
 [288655.40540541]
 [288655.40540541]
 [288655.40540541]
 [288655.40540541]
 [288655.40540541]
 [300000.        ]
 [350000.        ]
 [288655.40540541]
 [288655.40540541]
 [380000.        ]
 [233000.        ]
 [288655.40540541]
 [250000.        ]
 [288655.40540541]
 [230000.        ]
 [288655.40540541]
 [300000.        ]
 [270000.        ]
 [250000.        ]
 [240000.        ]
 [300000.        ]
 [280000.        ]
 [350000.        ]
 [250000.        ]
 [500000.        ]
 [288655.40540541]
 [204000.        ]
 [216000.        ]
 [300000.   

In [22]:
print(y_test)

[[300000.        ]
 [295000.        ]
 [250000.        ]
 [220000.        ]
 [200000.        ]
 [288655.40540541]
 [288655.40540541]
 [218000.        ]
 [210000.        ]
 [220000.        ]
 [288655.40540541]
 [250000.        ]
 [288655.40540541]
 [288655.40540541]
 [275000.        ]
 [288655.40540541]
 [290000.        ]
 [288655.40540541]
 [340000.        ]
 [275000.        ]
 [252000.        ]
 [260000.        ]
 [288655.40540541]
 [288655.40540541]
 [360000.        ]
 [400000.        ]
 [288655.40540541]
 [300000.        ]
 [288655.40540541]
 [690000.        ]
 [300000.        ]
 [220000.        ]
 [250000.        ]
 [264000.        ]
 [250000.        ]
 [400000.        ]
 [288655.40540541]
 [200000.        ]
 [276000.        ]
 [220000.        ]
 [300000.        ]
 [276000.        ]
 [240000.        ]]
